# Generated by Django 3.2 on 2021-04-20 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=30)),
                ('cmd', models.TextField(max_length=1000)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CustomBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmd_args', models.TextField(max_length=1000)),
                ('add_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('N', 'NEW'), ('P', 'PROGRESSING'), ('E', 'ENDED OK'), ('F', 'FAILED'), ('L', 'LOCKED'), ('T', 'TERMINATED')], max_length=1)),
                ('record_active_ind', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], default='Y', max_length=1)),
                ('add_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ref_batch_add_user_id_custom_batch', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ref_target', to='caseapplication.target')),
                ('update_user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ref_batch_update_user_id_custom_batch', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('03-2021', '03-2021'), ('02-2021', '02-2021'), ('01-2021', '01-2021'), ('12-2020', '12-2020'), ('11-2020', '11-2020'), ('10-2020', '10-2020'), ('09-2020', '09-2020'), ('08-2020', '08-2020'), ('07-2020', '07-2020'), ('06-2020', '06-2020'), ('05-2020', '05-2020'), ('04-2020', '04-2020'), ('03-2020', '03-2020'), ('02-2020', '02-2020'), ('01-2020', '01-2020'), ('12-2019', '12-2019'), ('11-2019', '11-2019'), ('10-2019', '10-2019'), ('09-2019', '09-2019'), ('08-2019', '08-2019'), ('07-2019', '07-2019'), ('06-2019', '06-2019'), ('05-2019', '05-2019'), ('04-2019', '04-2019'), ('03-2019', '03-2019'), ('02-2019', '02-2019'), ('01-2019', '01-2019'), ('12-2018', '12-2018'), ('11-2018', '11-2018'), ('10-2018', '10-2018'), ('09-2018', '09-2018'), ('08-2018', '08-2018'), ('07-2018', '07-2018'), ('06-2018', '06-2018'), ('05-2018', '05-2018'), ('04-2018', '04-2018')], max_length=20)),
                ('case_type', models.CharField(choices=[('A', 'CASE 1 - ManualAccrualToAlocation'), ('B', 'CASE 2 - Postings'), ('C', 'CASE 3 - InvoiceLineDetail'), ('E', 'CASE 5 -  InvoicePaymentPosting')], max_length=1)),
                ('add_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('N', 'NEW'), ('P', 'PROGRESSING'), ('E', 'ENDED OK'), ('F', 'FAILED'), ('L', 'LOCKED'), ('T', 'TERMINATED')], max_length=1)),
                ('record_active_ind', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], default='Y', max_length=1)),
                ('add_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ref_add_user_id', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_product', to='caseapplication.product')),
                ('update_user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ref_update_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmd', models.TextField(max_length=1000)),
                ('add_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('N', 'NEW'), ('P', 'PROGRESSING'), ('E', 'ENDED OK'), ('F', 'FAILED'), ('L', 'LOCKED'), ('T', 'TERMINATED')], max_length=1)),
                ('record_active_ind', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], default='Y', max_length=1)),
                ('add_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ref_batch_add_user_id', to=settings.AUTH_USER_MODEL)),
                ('update_user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ref_batch_update_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
